---

- name: upgrade all packages
  hosts: vps
  gather_facts: true
  tasks:
    - name: upgrading packages on Debian based servers
      apt:
        name: "*"
        state: latest
        update_cache: yes
        autoremove: yes
        autoclean: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: upgrading packages on RedHat based servers
      yum:
        name: "*"
        state: latest
        update_cache: yes
      when: ansible_facts['os_family'] == "RedHat"
    - name: removing unused packages on RedHat based servers
      yum:
        autoremove: true
      when: ansible_facts['os_family'] == "RedHat"