---
- name: Install docker
  hosts: all
  gather_facts: true
  tasks:
    - name: Block for Debian and Ubuntu
      block:
        - name: Install required packages
          ansible.builtin.apt:
            autoclean: true
            autoremove: true
            name:
              - ca-certificates
              - curl
              - gnupg
            update_cache: true

        - name: Add Docker GPG key
          ansible.builtin.apt_key:
            url: https://download.docker.com/linux/debian/gpg
            keyring: /etc/apt/keyrings/docker.gpg
            state: present

        - name: Set architecture variable
          ansible.builtin.set_fact:
            repoarch: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"

        - name: Add specified repository into sources list using specified filename
          ansible.builtin.apt_repository:
            repo: >-
              'deb [arch="{{ repoarch }}" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com
              /linux/{{ ansible_distribution|lower }} "{{ ansible_lsb.codename }}" stable'
            state: present
            filename: docker

        - name: Install Docker
          ansible.builtin.apt:
            autoclean: true
            autoremove: true
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-buildx-plugin
              - docker-compose-plugin
            update_cache: true

      when: ansible_facts['distribution'] == "Debian" or ansible_facts['distribution'] == "Ubuntu"
