#playbook for website hosting with ssh access 
---

- name: check disk usage
  hosts: hostings
  gather_facts: false
  tasks:
    - name: including vars from env.yml
      include_vars: env.yml

    - name: retrieving folder path
      command: pwd
      register: folder_path

    - name: retrieving disk usage
      command: du -s {{ folder_path.stdout }}
      register: usage

    - name: calculating used space
      set_fact:
        used_space: "{{ ((usage.stdout|regex_search('^[^\\t]+'))|int / 1024 / 1024)|round(2) }}"
    
    - name: calculating used space in percent
      set_fact:
        used_percent: "{{ (used_space|float / available_space_gb * 100) | float | round(2) }}"




    - name: checking if disk usage is below threshold
      block:
        - name: asserting that usage is below threshold
          assert:
            that:
              - used_percent|float <= disk_usage_threshold_percent|default(80)
            fail_msg: "WARNING, web hosting {{ inventory_hostname }} / {{ ansible_host }} exceeded disk usage threshold of {{ disk_usage_threshold_percent|default(80) }}%, current disk usage: {{ used_percent }}%"
            success_msg: "Current disk usage: {{ used_percent }}%"
      rescue:
        - set_fact:
            alert_message: "WARNING,%20web%20hosting%20{{ inventory_hostname }}%20/%20{{ ansible_host }}%20exceeded%20disk%20usage%20threshold%20of%20{{ disk_usage_threshold_percent|default(80) }}%%0Acurrent%20disk%20usage:%20{{ used_percent }}%"

        - name: sending telegram alert about exceeded threshold
          uri:
            url: https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage?chat_id={{ telegram_chat_id }}&text={{ alert_message }}
            method: POST
