---

- hosts: vps
  gather_facts: true
  tasks:
    - name: including vars from env.yml
      include_vars: env.yml

    - name: check services
      include_tasks: check_services.yml
      loop: "{{ services }}"
      when: services is defined