---
- hosts: all
  #for testing
# - hosts: 127.0.0.1
#   connection: local
  vars:
    ansible_user: root
    services:
      - squid
  tasks:
    - name: check services
      include_tasks: check_services.yml
      loop: "{{ services }}"