---
- name: check disk usage
  hosts: all
  # hosts: 127.0.0.1
  # connection: local
  tasks:
    - set_fact:
        mount: "{{ ansible_mounts | first }}"
    - set_fact:
        used_space: "{{ mount.size_total - mount.size_available }}"
    - set_fact:
        used_percent: "{{ (used_space|int) / (mount.size_total|int ) * 100 }}"
    - name: test msg
      assert:
        that:
          - (used_percent | int) <= 90
        fail_msg: "failed, disk usage {{ used_percent|int }}%"
        success_msg: "success, disk usage {{ used_percent|int }}%"